# Use archlinux:latest as parent image
FROM bgameiro/arch-doctools:latest

# Set maintainer
LABEL maintainer='BGameiro <projects+docker@bgameiro.me>'

# Update and install hugo and sphinx
RUN pacman --noconfirm -Syyu hugo