# Use specific version of zadam's trilium so that automatic updates don't brake installations
FROM zadam/trilium:0.46.7
#FROM zadam/trilium:0.46-latest
#FROM zadam/trilium:0.47-latest
#FROM zadam/trilium:0.48-latest
#FROM zadam/trilium:0.49-latest
#FROM zadam/trilium:0.50-latest
#FROM zadam/trilium:0.51-latest
#FROM zadam/trilium:0.52-latest
#FROM zadam/trilium:0.53-latest
#FROM zadam/trilium:0.54-latest

# Set maintainer
LABEL maintainer='BGameiro <projects+docker@bgameiro.me>'
