# Use specific version of zadam's trilium so that automatic updates don't brake installations
FROM zadam/trilium:0.46.7
#FROM zadam/trilium:0.47.8
#FROM zadam/trilium:0.48.9
#FROM zadam/trilium:0.49.5
#FROM zadam/trilium:0.50.3
#FROM zadam/trilium:0.51.2
#FROM zadam/trilium:0.52.3
#FROM zadam/trilium:0.53.2
#FROM zadam/trilium:0.54.2

# Set maintainer
LABEL maintainer='BGameiro <projects+docker@bgameiro.me>'
