# Use archlinux:latest as parent image
FROM archlinux:latest

# Set maintainer
LABEL maintainer='BGameiro <projects+docker@bgameiro.me>'

# Update and install texlive and poppler
RUN pacman --noconfirm -Syyu texlive-most texlive-lang poppler